version: '3'
services:
  database:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: "root"
        POSTGRES_PASSWORD: "root"
        POSTGRES_DB: "db"
    volumes:
      - ./docker-misc/postgres-init:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  webapp:
    build: ./
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - "database"

volumes:
  postgres: