version: '3'
services:
  database:
    build: ./docker-misc/postgres/
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db #db for webapp
      - RUNNER_DB=runner_db #db for runner
    ports:
      - '5432:5432'
  webapp:
    build: ./
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/app #to change when deploying to production
      - /app/node_modules
    links:
      - "database"
  runner:
    container_name: runner
    build: ./runner
    restart: always
    depends_on:
      - "database"
    links:
      - "database"
    ports:
      - '10000:10000' #meant for script at portainer within VPC to communicate.
volumes:
  postgres: