version: '3.7'
services:
  database:
    image: postgres
    restart: always
    environment: 
        POSTGRES_USER: "root"
        POSTGRES_PASSWORD: "root"
        POSTGRES_DB: 'db'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  webapp:
    build: ./
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - "database"            
volumes: 
  postgres:
