version: '3.7'
services:
  database:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: "root"
        POSTGRES_PASSWORD: "root"
        POSTGRES_DB: "db"
    volumes:
      - ./docker-misc/postgres-init:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  Nginx:
    container_name: Nginx
    hostname: Nginx
    image: nginx
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker-misc/nginx:/etc/nginx/conf.d:ro
      - ./docker-misc/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    links:
      - "webapp"
  webapp:
    build: ./
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
    depends_on:
      - "runner"
    links:
      - "database"
      - "runner"
  runner:
    container_name: runner
    build:
      context: ./runner
    restart: always
    depends_on:
      - "database"
    links:
      - "database"
volumes:
  postgres:
