version: '3.7'
services:
  database:
    image: mysql:latest
    restart: always
    environment: 
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_ROOT_HOST: '%'
    ports:
        - "3306:3306"
    expose:
        - '3306'
    volumes:
      - mysql:/var/lib/mysql
  webapp:
    build: ./
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
            
volumes: #define our mysql volume used above
  node_modules:
  mysql:
