version: '3.1'

services:
  database:
    image: mysql:latest
    container_name: devsql
    restart: always
    environment: 
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_ROOT_HOST: '%'
    ports:
        - "3306:3306"
    expose:
      - '3306'