version: '3.7'
services:
  database:
    image: mysql:latest
    container_name: devsql
    restart: always
    environment: 
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_ROOT_HOST: '%'
    ports:
        - "3306:3306"
    expose:
        - '3306'
    volumes:
      - mysql:/var/lib/mysql
  webapp:
    build: ./
    container_name: webApp
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/app

volumes: #define our mysql volume used above
  mysql:
